
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package compiler;

import java_cup.runtime.*;
import java.util.ArrayList;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class Parser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public Parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public Parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public Parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\071\000\002\002\004\000\002\002\003\000\002\003" +
    "\003\000\002\003\004\000\002\004\010\000\002\004\012" +
    "\000\002\005\002\000\002\005\004\000\002\006\014\000" +
    "\002\006\010\000\002\006\006\000\002\007\002\000\002" +
    "\007\003\000\002\007\005\000\002\010\005\000\002\011" +
    "\004\000\002\011\005\000\002\013\003\000\002\013\004" +
    "\000\002\014\010\000\002\015\003\000\002\015\005\000" +
    "\002\016\005\000\002\016\007\000\002\016\007\000\002" +
    "\016\011\000\002\012\005\000\002\012\011\000\002\012" +
    "\012\000\002\012\007\000\002\012\010\000\002\012\005" +
    "\000\002\012\006\000\002\012\011\000\002\012\007\000" +
    "\002\012\005\000\002\012\010\000\002\012\012\000\002" +
    "\012\012\000\002\012\007\000\002\012\004\000\002\012" +
    "\004\000\002\012\004\000\002\012\004\000\002\012\005" +
    "\000\002\012\005\000\002\012\005\000\002\012\005\000" +
    "\002\012\005\000\002\012\005\000\002\012\005\000\002" +
    "\012\005\000\002\012\003\000\002\012\003\000\002\012" +
    "\003\000\002\012\003\000\002\012\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\227\000\004\004\007\001\002\000\006\002\000\004" +
    "\007\001\002\000\004\002\230\001\002\000\006\002\uffff" +
    "\004\uffff\001\002\000\004\030\010\001\002\000\006\011" +
    "\012\051\011\001\002\000\006\027\ufffb\052\ufffb\001\002" +
    "\000\004\030\013\001\002\000\004\051\014\001\002\000" +
    "\006\027\ufffb\052\ufffb\001\002\000\006\027\016\052\020" +
    "\001\002\000\006\047\023\053\022\001\002\000\006\027" +
    "\ufffa\052\ufffa\001\002\000\004\054\021\001\002\000\006" +
    "\002\ufffc\004\ufffc\001\002\000\004\030\220\001\002\000" +
    "\010\027\024\050\ufff6\055\ufff6\001\002\000\004\053\216" +
    "\001\002\000\006\050\030\055\027\001\002\000\006\050" +
    "\ufff5\055\ufff5\001\002\000\004\027\024\001\002\000\004" +
    "\053\031\001\002\000\004\030\032\001\002\000\004\051" +
    "\033\001\002\000\040\007\042\012\044\013\052\017\034" +
    "\020\046\022\037\024\050\025\040\026\043\027\045\031" +
    "\041\032\036\044\051\047\053\051\035\001\002\000\040" +
    "\007\042\012\044\013\052\017\034\020\046\022\037\024" +
    "\050\025\040\026\043\027\045\031\041\032\036\044\051" +
    "\047\053\051\035\001\002\000\040\007\042\012\044\013" +
    "\052\017\034\020\046\022\037\024\050\025\040\026\043" +
    "\027\045\031\041\032\036\044\051\047\053\051\035\001" +
    "\002\000\052\005\uffcc\006\uffcc\010\uffcc\014\uffcc\015\uffcc" +
    "\016\uffcc\023\uffcc\035\uffcc\036\uffcc\037\uffcc\040\uffcc\041" +
    "\uffcc\042\uffcc\043\uffcc\045\uffcc\046\uffcc\050\uffcc\052\uffcc" +
    "\054\uffcc\055\uffcc\001\002\000\004\030\202\001\002\000" +
    "\052\005\uffca\006\uffca\010\uffca\014\uffca\015\uffca\016\uffca" +
    "\023\uffca\035\uffca\036\uffca\037\uffca\040\uffca\041\uffca\042" +
    "\uffca\043\uffca\045\uffca\046\uffca\050\uffca\052\uffca\054\uffca" +
    "\055\uffca\001\002\000\052\005\uffcb\006\uffcb\010\uffcb\014" +
    "\uffcb\015\uffcb\016\uffcb\023\uffcb\035\uffcb\036\uffcb\037\uffcb" +
    "\040\uffcb\041\uffcb\042\uffcb\043\uffcb\045\uffcb\046\uffcb\050" +
    "\uffcb\052\uffcb\054\uffcb\055\uffcb\001\002\000\040\007\042" +
    "\012\044\013\052\017\034\020\046\022\037\024\050\025" +
    "\040\026\043\027\045\031\041\032\036\044\051\047\053" +
    "\051\035\001\002\000\052\005\uffc9\006\uffc9\010\uffc9\014" +
    "\uffc9\015\uffc9\016\uffc9\023\uffc9\035\uffc9\036\uffc9\037\uffc9" +
    "\040\uffc9\041\uffc9\042\uffc9\043\uffc9\045\uffc9\046\uffc9\050" +
    "\uffc9\052\uffc9\054\uffc9\055\uffc9\001\002\000\040\007\042" +
    "\012\044\013\052\017\034\020\046\022\037\024\050\025" +
    "\040\026\043\027\045\031\041\032\036\044\051\047\053" +
    "\051\035\001\002\000\056\005\uffcd\006\uffcd\010\uffcd\014" +
    "\uffcd\015\uffcd\016\uffcd\023\uffcd\033\166\035\uffcd\036\uffcd" +
    "\037\uffcd\040\uffcd\041\uffcd\042\uffcd\043\uffcd\045\uffcd\046" +
    "\uffcd\047\165\050\uffcd\052\uffcd\054\uffcd\055\uffcd\001\002" +
    "\000\040\007\042\012\044\013\052\017\034\020\046\022" +
    "\037\024\050\025\040\026\043\027\045\031\041\032\036" +
    "\044\051\047\053\051\035\001\002\000\026\035\061\036" +
    "\066\037\060\040\057\041\055\042\056\043\063\045\065" +
    "\046\062\052\147\001\002\000\040\007\042\012\044\013" +
    "\052\017\034\020\046\022\037\024\050\025\040\026\043" +
    "\027\045\031\041\032\036\044\051\047\053\051\035\001" +
    "\002\000\040\007\042\012\044\013\052\017\034\020\046" +
    "\022\037\024\050\025\040\026\043\027\045\031\041\032" +
    "\036\044\051\047\053\051\035\001\002\000\004\027\115" +
    "\001\002\000\040\007\042\012\044\013\052\017\034\020" +
    "\046\022\037\024\050\025\040\026\043\027\045\031\041" +
    "\032\036\044\051\047\053\051\035\001\002\000\026\035" +
    "\061\036\066\037\060\040\057\041\055\042\056\043\063" +
    "\045\065\046\062\050\064\001\002\000\040\007\042\012" +
    "\044\013\052\017\034\020\046\022\037\024\050\025\040" +
    "\026\043\027\045\031\041\032\036\044\051\047\053\051" +
    "\035\001\002\000\040\007\042\012\044\013\052\017\034" +
    "\020\046\022\037\024\050\025\040\026\043\027\045\031" +
    "\041\032\036\044\051\047\053\051\035\001\002\000\040" +
    "\007\042\012\044\013\052\017\034\020\046\022\037\024" +
    "\050\025\040\026\043\027\045\031\041\032\036\044\051" +
    "\047\053\051\035\001\002\000\040\007\042\012\044\013" +
    "\052\017\034\020\046\022\037\024\050\025\040\026\043" +
    "\027\045\031\041\032\036\044\051\047\053\051\035\001" +
    "\002\000\040\007\042\012\044\013\052\017\034\020\046" +
    "\022\037\024\050\025\040\026\043\027\045\031\041\032" +
    "\036\044\051\047\053\051\035\001\002\000\004\027\103" +
    "\001\002\000\040\007\042\012\044\013\052\017\034\020" +
    "\046\022\037\024\050\025\040\026\043\027\045\031\041" +
    "\032\036\044\051\047\053\051\035\001\002\000\052\005" +
    "\uffce\006\uffce\010\uffce\014\uffce\015\uffce\016\uffce\023\uffce" +
    "\035\uffce\036\uffce\037\uffce\040\uffce\041\uffce\042\uffce\043" +
    "\uffce\045\uffce\046\uffce\050\uffce\052\uffce\054\uffce\055\uffce" +
    "\001\002\000\004\030\070\001\002\000\040\007\042\012" +
    "\044\013\052\017\034\020\046\022\037\024\050\025\040" +
    "\026\043\027\045\031\041\032\036\044\051\047\053\051" +
    "\035\001\002\000\044\005\uffd1\006\uffd1\010\uffd1\014\uffd1" +
    "\015\uffd1\016\uffd1\023\uffd1\040\057\041\055\042\056\043" +
    "\063\045\065\046\062\050\uffd1\052\uffd1\054\uffd1\055\uffd1" +
    "\001\002\000\004\046\071\001\002\000\004\027\072\001" +
    "\002\000\004\047\073\001\002\000\042\007\042\012\044" +
    "\013\052\017\034\020\046\022\037\024\050\025\040\026" +
    "\043\027\045\031\041\032\036\044\051\047\053\050\075" +
    "\051\035\001\002\000\030\035\061\036\066\037\060\040" +
    "\057\041\055\042\056\043\063\045\065\046\062\050\uffed" +
    "\055\uffed\001\002\000\052\005\uffe6\006\uffe6\010\uffe6\014" +
    "\uffe6\015\uffe6\016\uffe6\023\uffe6\035\uffe6\036\uffe6\037\uffe6" +
    "\040\uffe6\041\uffe6\042\uffe6\043\uffe6\045\uffe6\046\uffe6\050" +
    "\uffe6\052\uffe6\054\uffe6\055\uffe6\001\002\000\006\050\100" +
    "\055\077\001\002\000\040\007\042\012\044\013\052\017" +
    "\034\020\046\022\037\024\050\025\040\026\043\027\045" +
    "\031\041\032\036\044\051\047\053\051\035\001\002\000" +
    "\052\005\uffe5\006\uffe5\010\uffe5\014\uffe5\015\uffe5\016\uffe5" +
    "\023\uffe5\035\uffe5\036\uffe5\037\uffe5\040\uffe5\041\uffe5\042" +
    "\uffe5\043\uffe5\045\uffe5\046\uffe5\050\uffe5\052\uffe5\054\uffe5" +
    "\055\uffe5\001\002\000\030\035\061\036\066\037\060\040" +
    "\057\041\055\042\056\043\063\045\065\046\062\050\uffec" +
    "\055\uffec\001\002\000\052\005\uffd2\006\uffd2\010\uffd2\014" +
    "\uffd2\015\uffd2\016\uffd2\023\uffd2\035\uffd2\036\uffd2\037\uffd2" +
    "\040\uffd2\041\uffd2\042\uffd2\043\uffd2\045\065\046\062\050" +
    "\uffd2\052\uffd2\054\uffd2\055\uffd2\001\002\000\004\047\104" +
    "\001\002\000\042\007\042\012\044\013\052\017\034\020" +
    "\046\022\037\024\050\025\040\026\043\027\045\031\041" +
    "\032\036\044\051\047\053\050\105\051\035\001\002\000" +
    "\052\005\uffe4\006\uffe4\010\uffe4\014\uffe4\015\uffe4\016\uffe4" +
    "\023\uffe4\035\uffe4\036\uffe4\037\uffe4\040\uffe4\041\uffe4\042" +
    "\uffe4\043\uffe4\045\uffe4\046\uffe4\050\uffe4\052\uffe4\054\uffe4" +
    "\055\uffe4\001\002\000\006\050\107\055\077\001\002\000" +
    "\052\005\uffe3\006\uffe3\010\uffe3\014\uffe3\015\uffe3\016\uffe3" +
    "\023\uffe3\035\uffe3\036\uffe3\037\uffe3\040\uffe3\041\uffe3\042" +
    "\uffe3\043\uffe3\045\uffe3\046\uffe3\050\uffe3\052\uffe3\054\uffe3" +
    "\055\uffe3\001\002\000\044\005\uffd0\006\uffd0\010\uffd0\014" +
    "\uffd0\015\uffd0\016\uffd0\023\uffd0\040\057\041\055\042\056" +
    "\043\063\045\065\046\062\050\uffd0\052\uffd0\054\uffd0\055" +
    "\uffd0\001\002\000\044\005\uffcf\006\uffcf\010\uffcf\014\uffcf" +
    "\015\uffcf\016\uffcf\023\uffcf\040\057\041\055\042\056\043" +
    "\063\045\065\046\062\050\uffcf\052\uffcf\054\uffcf\055\uffcf" +
    "\001\002\000\052\005\uffd5\006\uffd5\010\uffd5\014\uffd5\015" +
    "\uffd5\016\uffd5\023\uffd5\035\uffd5\036\uffd5\037\uffd5\040\uffd5" +
    "\041\uffd5\042\056\043\063\045\065\046\062\050\uffd5\052" +
    "\uffd5\054\uffd5\055\uffd5\001\002\000\052\005\uffd3\006\uffd3" +
    "\010\uffd3\014\uffd3\015\uffd3\016\uffd3\023\uffd3\035\uffd3\036" +
    "\uffd3\037\uffd3\040\uffd3\041\uffd3\042\uffd3\043\uffd3\045\065" +
    "\046\062\050\uffd3\052\uffd3\054\uffd3\055\uffd3\001\002\000" +
    "\052\005\uffd4\006\uffd4\010\uffd4\014\uffd4\015\uffd4\016\uffd4" +
    "\023\uffd4\035\uffd4\036\uffd4\037\uffd4\040\uffd4\041\uffd4\042" +
    "\056\043\063\045\065\046\062\050\uffd4\052\uffd4\054\uffd4" +
    "\055\uffd4\001\002\000\004\053\116\001\002\000\004\030" +
    "\117\001\002\000\010\010\121\033\122\055\120\001\002" +
    "\000\004\027\127\001\002\000\040\007\042\012\044\013" +
    "\052\017\034\020\046\022\037\024\050\025\040\026\043" +
    "\027\045\031\041\032\036\044\051\047\053\051\035\001" +
    "\002\000\040\007\042\012\044\013\052\017\034\020\046" +
    "\022\037\024\050\025\040\026\043\027\045\031\041\032" +
    "\036\044\051\047\053\051\035\001\002\000\026\010\124" +
    "\035\061\036\066\037\060\040\057\041\055\042\056\043" +
    "\063\045\065\046\062\001\002\000\040\007\042\012\044" +
    "\013\052\017\034\020\046\022\037\024\050\025\040\026" +
    "\043\027\045\031\041\032\036\044\051\047\053\051\035" +
    "\001\002\000\052\005\uffdc\006\uffdc\010\uffdc\014\uffdc\015" +
    "\uffdc\016\uffdc\023\uffdc\035\061\036\066\037\060\040\057" +
    "\041\055\042\056\043\063\045\065\046\062\050\uffdc\052" +
    "\uffdc\054\uffdc\055\uffdc\001\002\000\052\005\uffdd\006\uffdd" +
    "\010\uffdd\014\uffdd\015\uffdd\016\uffdd\023\uffdd\035\061\036" +
    "\066\037\060\040\057\041\055\042\056\043\063\045\065" +
    "\046\062\050\uffdd\052\uffdd\054\uffdd\055\uffdd\001\002\000" +
    "\004\053\141\001\002\000\006\010\132\055\131\001\002" +
    "\000\004\027\134\001\002\000\040\007\042\012\044\013" +
    "\052\017\034\020\046\022\037\024\050\025\040\026\043" +
    "\027\045\031\041\032\036\044\051\047\053\051\035\001" +
    "\002\000\052\005\uffdb\006\uffdb\010\uffdb\014\uffdb\015\uffdb" +
    "\016\uffdb\023\uffdb\035\061\036\066\037\060\040\057\041" +
    "\055\042\056\043\063\045\065\046\062\050\uffdb\052\uffdb" +
    "\054\uffdb\055\uffdb\001\002\000\004\053\135\001\002\000" +
    "\004\030\136\001\002\000\010\010\uffe9\033\137\055\uffe9" +
    "\001\002\000\040\007\042\012\044\013\052\017\034\020" +
    "\046\022\037\024\050\025\040\026\043\027\045\031\041" +
    "\032\036\044\051\047\053\051\035\001\002\000\030\010" +
    "\uffe8\035\061\036\066\037\060\040\057\041\055\042\056" +
    "\043\063\045\065\046\062\055\uffe8\001\002\000\004\030" +
    "\142\001\002\000\010\010\uffeb\033\143\055\uffeb\001\002" +
    "\000\040\007\042\012\044\013\052\017\034\020\046\022" +
    "\037\024\050\025\040\026\043\027\045\031\041\032\036" +
    "\044\051\047\053\051\035\001\002\000\030\010\uffea\035" +
    "\061\036\066\037\060\040\057\041\055\042\056\043\063" +
    "\045\065\046\062\055\uffea\001\002\000\052\005\uffd7\006" +
    "\uffd7\010\uffd7\014\uffd7\015\uffd7\016\uffd7\023\uffd7\035\uffd7" +
    "\036\uffd7\037\uffd7\040\uffd7\041\uffd7\042\uffd7\043\uffd7\045" +
    "\065\046\062\050\uffd7\052\uffd7\054\uffd7\055\uffd7\001\002" +
    "\000\052\005\uffd6\006\uffd6\010\uffd6\014\uffd6\015\uffd6\016" +
    "\uffd6\023\uffd6\035\061\036\066\037\060\040\057\041\055" +
    "\042\056\043\063\045\065\046\062\050\uffd6\052\uffd6\054" +
    "\uffd6\055\uffd6\001\002\000\004\054\150\001\002\000\006" +
    "\027\ufff9\052\ufff9\001\002\000\026\023\152\035\061\036" +
    "\066\037\060\040\057\041\055\042\056\043\063\045\065" +
    "\046\062\001\002\000\004\027\153\001\002\000\004\053" +
    "\160\001\002\000\006\021\ufff0\027\ufff0\001\002\000\006" +
    "\021\157\027\153\001\002\000\006\021\uffef\027\uffef\001" +
    "\002\000\052\005\uffda\006\uffda\010\uffda\014\uffda\015\uffda" +
    "\016\uffda\023\uffda\035\uffda\036\uffda\037\uffda\040\uffda\041" +
    "\uffda\042\uffda\043\uffda\045\uffda\046\uffda\050\uffda\052\uffda" +
    "\054\uffda\055\uffda\001\002\000\004\030\161\001\002\000" +
    "\004\034\162\001\002\000\040\007\042\012\044\013\052" +
    "\017\034\020\046\022\037\024\050\025\040\026\043\027" +
    "\045\031\041\032\036\044\051\047\053\051\035\001\002" +
    "\000\026\035\061\036\066\037\060\040\057\041\055\042" +
    "\056\043\063\045\065\046\062\054\164\001\002\000\006" +
    "\021\uffee\027\uffee\001\002\000\042\007\042\012\044\013" +
    "\052\017\034\020\046\022\037\024\050\025\040\026\043" +
    "\027\045\031\041\032\036\044\051\047\053\050\170\051" +
    "\035\001\002\000\040\007\042\012\044\013\052\017\034" +
    "\020\046\022\037\024\050\025\040\026\043\027\045\031" +
    "\041\032\036\044\051\047\053\051\035\001\002\000\052" +
    "\005\uffe7\006\uffe7\010\uffe7\014\uffe7\015\uffe7\016\uffe7\023" +
    "\uffe7\035\061\036\066\037\060\040\057\041\055\042\056" +
    "\043\063\045\065\046\062\050\uffe7\052\uffe7\054\uffe7\055" +
    "\uffe7\001\002\000\052\005\uffe2\006\uffe2\010\uffe2\014\uffe2" +
    "\015\uffe2\016\uffe2\023\uffe2\035\uffe2\036\uffe2\037\uffe2\040" +
    "\uffe2\041\uffe2\042\uffe2\043\uffe2\045\uffe2\046\uffe2\050\uffe2" +
    "\052\uffe2\054\uffe2\055\uffe2\001\002\000\006\050\172\055" +
    "\077\001\002\000\052\005\uffe1\006\uffe1\010\uffe1\014\uffe1" +
    "\015\uffe1\016\uffe1\023\uffe1\035\uffe1\036\uffe1\037\uffe1\040" +
    "\uffe1\041\uffe1\042\uffe1\043\uffe1\045\uffe1\046\uffe1\050\uffe1" +
    "\052\uffe1\054\uffe1\055\uffe1\001\002\000\052\005\uffd8\006" +
    "\uffd8\010\uffd8\014\uffd8\015\uffd8\016\uffd8\023\uffd8\035\uffd8" +
    "\036\uffd8\037\uffd8\040\uffd8\041\uffd8\042\uffd8\043\uffd8\045" +
    "\065\046\062\050\uffd8\052\uffd8\054\uffd8\055\uffd8\001\002" +
    "\000\026\016\175\035\061\036\066\037\060\040\057\041" +
    "\055\042\056\043\063\045\065\046\062\001\002\000\040" +
    "\007\042\012\044\013\052\017\034\020\046\022\037\024" +
    "\050\025\040\026\043\027\045\031\041\032\036\044\051" +
    "\047\053\051\035\001\002\000\026\005\177\035\061\036" +
    "\066\037\060\040\057\041\055\042\056\043\063\045\065" +
    "\046\062\001\002\000\040\007\042\012\044\013\052\017" +
    "\034\020\046\022\037\024\050\025\040\026\043\027\045" +
    "\031\041\032\036\044\051\047\053\051\035\001\002\000" +
    "\026\006\201\035\061\036\066\037\060\040\057\041\055" +
    "\042\056\043\063\045\065\046\062\001\002\000\052\005" +
    "\uffe0\006\uffe0\010\uffe0\014\uffe0\015\uffe0\016\uffe0\023\uffe0" +
    "\035\uffe0\036\uffe0\037\uffe0\040\uffe0\041\uffe0\042\uffe0\043" +
    "\uffe0\045\uffe0\046\uffe0\050\uffe0\052\uffe0\054\uffe0\055\uffe0" +
    "\001\002\000\052\005\uffd9\006\uffd9\010\uffd9\014\uffd9\015" +
    "\uffd9\016\uffd9\023\uffd9\035\uffd9\036\uffd9\037\uffd9\040\uffd9" +
    "\041\uffd9\042\uffd9\043\uffd9\045\uffd9\046\uffd9\050\uffd9\052" +
    "\uffd9\054\uffd9\055\uffd9\001\002\000\042\007\042\012\044" +
    "\013\052\017\034\020\046\022\037\024\050\025\040\026" +
    "\043\027\045\031\041\032\036\044\051\047\053\051\035" +
    "\052\207\001\002\000\026\035\061\036\066\037\060\040" +
    "\057\041\055\042\056\043\063\045\065\046\062\054\205" +
    "\001\002\000\042\007\ufff2\012\ufff2\013\ufff2\017\ufff2\020" +
    "\ufff2\022\ufff2\024\ufff2\025\ufff2\026\ufff2\027\ufff2\031\ufff2" +
    "\032\ufff2\044\ufff2\047\ufff2\051\ufff2\052\ufff2\001\002\000" +
    "\026\035\061\036\066\037\060\040\057\041\055\042\056" +
    "\043\063\045\065\046\062\054\210\001\002\000\052\005" +
    "\uffde\006\uffde\010\uffde\014\uffde\015\uffde\016\uffde\023\uffde" +
    "\035\uffde\036\uffde\037\uffde\040\uffde\041\uffde\042\uffde\043" +
    "\uffde\045\uffde\046\uffde\050\uffde\052\uffde\054\uffde\055\uffde" +
    "\001\002\000\042\007\ufff1\012\ufff1\013\ufff1\017\ufff1\020" +
    "\ufff1\022\ufff1\024\ufff1\025\ufff1\026\ufff1\027\ufff1\031\ufff1" +
    "\032\ufff1\044\ufff1\047\ufff1\051\ufff1\052\ufff1\001\002\000" +
    "\026\014\212\035\061\036\066\037\060\040\057\041\055" +
    "\042\056\043\063\045\065\046\062\001\002\000\040\007" +
    "\042\012\044\013\052\017\034\020\046\022\037\024\050" +
    "\025\040\026\043\027\045\031\041\032\036\044\051\047" +
    "\053\051\035\001\002\000\026\015\214\035\061\036\066" +
    "\037\060\040\057\041\055\042\056\043\063\045\065\046" +
    "\062\001\002\000\052\005\uffdf\006\uffdf\010\uffdf\014\uffdf" +
    "\015\uffdf\016\uffdf\023\uffdf\035\uffdf\036\uffdf\037\uffdf\040" +
    "\uffdf\041\uffdf\042\uffdf\043\uffdf\045\uffdf\046\uffdf\050\uffdf" +
    "\052\uffdf\054\uffdf\055\uffdf\001\002\000\006\050\ufff4\055" +
    "\ufff4\001\002\000\004\030\217\001\002\000\006\050\ufff3" +
    "\055\ufff3\001\002\000\006\033\222\054\221\001\002\000" +
    "\006\027\ufff7\052\ufff7\001\002\000\040\007\042\012\044" +
    "\013\052\017\034\020\046\022\037\024\050\025\040\026" +
    "\043\027\045\031\041\032\036\044\051\047\053\051\035" +
    "\001\002\000\026\035\061\036\066\037\060\040\057\041" +
    "\055\042\056\043\063\045\065\046\062\054\224\001\002" +
    "\000\006\027\ufff8\052\ufff8\001\002\000\006\027\016\052" +
    "\226\001\002\000\004\054\227\001\002\000\006\002\ufffd" +
    "\004\ufffd\001\002\000\004\002\001\001\002\000\006\002" +
    "\ufffe\004\ufffe\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\227\000\010\002\004\003\003\004\005\001\001\000" +
    "\004\004\230\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\005\224\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\005\014" +
    "\001\001\000\004\006\016\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\006\007\024\010\025\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\010\214" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\012\046\001\001\000\004\012\210\001\001" +
    "\000\006\011\202\012\203\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\012\173\001\001\000\002\001\001\000\004\012\172\001" +
    "\001\000\002\001\001\000\004\012\150\001\001\000\002" +
    "\001\001\000\004\012\145\001\001\000\004\012\144\001" +
    "\001\000\002\001\001\000\004\012\053\001\001\000\002" +
    "\001\001\000\004\012\113\001\001\000\004\012\112\001" +
    "\001\000\004\012\111\001\001\000\004\012\110\001\001" +
    "\000\004\012\107\001\001\000\002\001\001\000\004\012" +
    "\101\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\012\066\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\006\012\073\015\075" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\012\100\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\006\012" +
    "\073\015\105\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\016" +
    "\127\001\001\000\004\012\125\001\001\000\004\012\122" +
    "\001\001\000\002\001\001\000\004\012\124\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\012\132\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\012\137\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\012\143\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\006" +
    "\013\154\014\153\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\014\155\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\012" +
    "\162\001\001\000\002\001\001\000\002\001\001\000\006" +
    "\012\073\015\170\001\001\000\004\012\166\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\012" +
    "\175\001\001\000\002\001\001\000\004\012\177\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\012\205\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\012\212\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\012\222\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\006\016\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$Parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$Parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$Parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}




    /* Erros de sintaxe não fatais */
    public void report_error(String message, Object info) {
        StringBuilder m = new StringBuilder("Erro Sintático");

        if (info instanceof java_cup.runtime.Symbol) {
            java_cup.runtime.Symbol s = ((java_cup.runtime.Symbol) info);
            if (s.left >= 0) {
                m.append(" na linha " + (s.left));
                if (s.right >= 0)
                    m.append(", coluna " + (s.right));
            }
            if (s.value != null) {
                m.append(". Token inesperado: " + s.value);
            }
        }
        m.append(" : " + message);
        System.err.println(m);
    }

    /* Erros de sintaxe fatais */
    public void report_fatal_error(String message, Object info) {
        report_error(message, info);
        System.exit(1);
    }

    public void checkNotSelf(String id, int line, int col) {
        if ("self".equals(id)) {
            java_cup.runtime.Symbol s = new java_cup.runtime.Symbol(sym.ID, line, col, id);
            report_fatal_error("Uso ilegal de 'self' como identificador", s);
        }
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$Parser$actions {
  private final Parser parser;

  /** Constructor */
  CUP$Parser$actions(Parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$Parser$do_action_part00000000(
    int                        CUP$Parser$act_num,
    java_cup.runtime.lr_parser CUP$Parser$parser,
    java.util.Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$Parser$result;

      /* select the action based on the action number */
      switch (CUP$Parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= program EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		RESULT = start_val;
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$Parser$parser.done_parsing();
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // program ::= class_list 
            {
              Object RESULT =null;
		 System.out.println("=== Análise Sintática Concluída com Sucesso! ==="); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("program",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // class_list ::= class_decl 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("class_list",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // class_list ::= class_list class_decl 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("class_list",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // class_decl ::= CLASS TYPEID LBRACE feature_list RBRACE SEMI 
            {
              Object RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-4)).value;
		 System.out.println("[CLASSE] Definida: " + n); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("class_decl",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // class_decl ::= CLASS TYPEID INHERITS TYPEID LBRACE feature_list RBRACE SEMI 
            {
              Object RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-6)).value;
		int pleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).left;
		int pright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).right;
		String p = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-4)).value;
		 System.out.println("[CLASSE] Definida: " + n + " herda de " + p); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("class_decl",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // feature_list ::= 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("feature_list",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // feature_list ::= feature_list feature 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("feature_list",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // feature ::= ID LPAREN formal_list RPAREN COLON TYPEID LBRACE expr RBRACE SEMI 
            {
              Object RESULT =null;
		int nameleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-9)).left;
		int nameright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-9)).right;
		String name = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-9)).value;
		int typeleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).left;
		int typeright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).right;
		String type = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-4)).value;
		 System.out.println(" --- Método: " + name + " retorna " + type); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("feature",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-9)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // feature ::= ID COLON TYPEID ASSIGN expr SEMI 
            {
              Object RESULT =null;
		int nameleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)).left;
		int nameright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)).right;
		String name = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-5)).value;
		int typeleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int typeright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		String type = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		 System.out.println(" --- Atributo: " + name + " : " + type);
         checkNotSelf(name, nameleft, nameright);  
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("feature",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // feature ::= ID COLON TYPEID SEMI 
            {
              Object RESULT =null;
		int nameleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int nameright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		String name = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int typeleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int typeright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String type = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 System.out.println(" --- Atributo: " + name + " : " + type);
         checkNotSelf(name, nameleft, nameright);  
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("feature",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // formal_list ::= 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("formal_list",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // formal_list ::= formal 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("formal_list",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // formal_list ::= formal_list COMMA formal 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("formal_list",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // formal ::= ID COLON TYPEID 
            {
              Object RESULT =null;
		int nameleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int nameright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String name = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int typeleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int typeright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String type = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 System.out.println("    (Parametro formal: " + name + " : " + type + ")");
    checkNotSelf(name, nameleft, nameright); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("formal",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // expr_list ::= expr SEMI 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr_list",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // expr_list ::= expr_list expr SEMI 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr_list",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // case_list ::= case_branch 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("case_list",9, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // case_list ::= case_list case_branch 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("case_list",9, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // case_branch ::= ID COLON TYPEID DARROW expr SEMI 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-5)).value;
		int typeleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int typeright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		String type = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		 System.out.println("    |-- Case Branch: " + id + " como " + type);
     checkNotSelf(id, idleft, idright); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("case_branch",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // argument_list ::= expr 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("argument_list",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // argument_list ::= argument_list COMMA expr 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("argument_list",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // let_list ::= ID COLON TYPEID 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int typeleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int typeright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String type = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 System.out.println("    |-- Var Let: " + id + " : " + type);
     checkNotSelf(id, idleft, idright); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("let_list",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // let_list ::= ID COLON TYPEID ASSIGN expr 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-4)).value;
		int typeleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int typeright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String type = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		 System.out.println("    |-- Var Let (com init): " + id);
    checkNotSelf(id, idleft, idright); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("let_list",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // let_list ::= let_list COMMA ID COLON TYPEID 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int typeleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int typeright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String type = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 System.out.println("    |-- Var Let: " + id);
    checkNotSelf(id, idleft, idright); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("let_list",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // let_list ::= let_list COMMA ID COLON TYPEID ASSIGN expr 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-4)).value;
		int typeleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int typeright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String type = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		 System.out.println("    |-- Var Let (com init): " + id);
     checkNotSelf(id, idleft, idright); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("let_list",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // expr ::= ID ASSIGN expr 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		 System.out.println("    |-- Atribuicao para variavel: " + id);
      checkNotSelf(id, idleft, idright); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // expr ::= expr AT TYPEID DOT ID LPAREN RPAREN 
            {
              Object RESULT =null;
		int typeleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).left;
		int typeright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).right;
		String type = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-4)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		 System.out.println("    |-- Static Dispatch @" + type + "." + id + "()"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // expr ::= expr AT TYPEID DOT ID LPAREN argument_list RPAREN 
            {
              Object RESULT =null;
		int typeleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)).left;
		int typeright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)).right;
		String type = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-5)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		 System.out.println("    |-- Static Dispatch @" + type + "." + id + "(...)"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // expr ::= expr DOT ID LPAREN RPAREN 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		 System.out.println("    |-- Dispatch para metodo: " + id + "()"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // expr ::= expr DOT ID LPAREN argument_list RPAREN 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		 System.out.println("    |-- Dispatch para metodo: " + id + "(args...)"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // expr ::= ID LPAREN RPAREN 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		 System.out.println("    |-- Chamada Self: " + id + "()"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // expr ::= ID LPAREN argument_list RPAREN 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		 System.out.println("    |-- Chamada Self: " + id + "(args...)"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // expr ::= IF expr THEN expr ELSE expr FI 
            {
              Object RESULT =null;
		 System.out.println("    |-- Estrutura Condicional (IF-THEN-ELSE)"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // expr ::= WHILE expr LOOP expr POOL 
            {
              Object RESULT =null;
		 System.out.println("    |-- Estrutura de Repeticao (WHILE)"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // expr ::= LBRACE expr_list RBRACE 
            {
              Object RESULT =null;
		 System.out.println("    |-- Bloco de codigo { ... }"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // expr ::= LET ID COLON TYPEID IN expr 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-4)).value;
		 System.out.println("    |-- Estrutura LET simples (" + id + ")");
     checkNotSelf(id, idleft, idright); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // expr ::= LET ID COLON TYPEID ASSIGN expr IN expr 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-6)).value;
		 System.out.println("    |-- Estrutura LET com init (" + id + ")");
     checkNotSelf(id, idleft, idright); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // expr ::= LET ID COLON TYPEID COMMA let_list IN expr 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-6)).value;
		 System.out.println("    |-- Estrutura LET multiplo (" + id + ", ...)");
     checkNotSelf(id, idleft, idright); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // expr ::= CASE expr OF case_list ESAC 
            {
              Object RESULT =null;
		 System.out.println("    |-- Estrutura CASE"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // expr ::= NEW TYPEID 
            {
              Object RESULT =null;
		int typeleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int typeright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String type = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 System.out.println("    |-- New (Instancia de " + type + ")"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // expr ::= ISVOID expr 
            {
              Object RESULT =null;
		 System.out.println("    |-- Teste ISVOID"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // expr ::= NEG expr 
            {
              Object RESULT =null;
		 System.out.println("    |-- Operacao de Negacao (~)"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // expr ::= NOT expr 
            {
              Object RESULT =null;
		 System.out.println("    |-- Operacao NOT"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // expr ::= expr PLUS expr 
            {
              Object RESULT =null;
		 System.out.println("    |-- Operacao SOMA (+)"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // expr ::= expr MINUS expr 
            {
              Object RESULT =null;
		 System.out.println("    |-- Operacao SUBTRACAO (-)"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // expr ::= expr MULT expr 
            {
              Object RESULT =null;
		 System.out.println("    |-- Operacao MULTIPLICACAO (*)"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // expr ::= expr DIV expr 
            {
              Object RESULT =null;
		 System.out.println("    |-- Operacao DIVISAO (/)"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // expr ::= expr LT expr 
            {
              Object RESULT =null;
		 System.out.println("    |-- Comparacao MENOR QUE (<)"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // expr ::= expr LE expr 
            {
              Object RESULT =null;
		 System.out.println("    |-- Comparacao MENOR IGUAL (<=)"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // expr ::= expr EQ expr 
            {
              Object RESULT =null;
		 System.out.println("    |-- Comparacao IGUAL (=)"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // expr ::= LPAREN expr RPAREN 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // expr ::= ID 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 System.out.println("    |-- ID lido: " + id); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // expr ::= INT_CONST 
            {
              Object RESULT =null;
		int valleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int valright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Integer val = (Integer)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 System.out.println("    |-- Inteiro lido: " + val); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // expr ::= STR_CONST 
            {
              Object RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String s = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 System.out.println("    |-- String lida: \"" + s + "\""); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // expr ::= TRUE 
            {
              Object RESULT =null;
		 System.out.println("    |-- Booleano: true"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // expr ::= FALSE 
            {
              Object RESULT =null;
		 System.out.println("    |-- Booleano: false"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$Parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$Parser$do_action(
    int                        CUP$Parser$act_num,
    java_cup.runtime.lr_parser CUP$Parser$parser,
    java.util.Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws java.lang.Exception
    {
              return CUP$Parser$do_action_part00000000(
                               CUP$Parser$act_num,
                               CUP$Parser$parser,
                               CUP$Parser$stack,
                               CUP$Parser$top);
    }
}

}
