
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package compiler;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int MULT = 32;
  public static final int INHERITS = 7;
  public static final int POOL = 11;
  public static final int CASE = 14;
  public static final int SEMI = 42;
  public static final int LPAREN = 37;
  public static final int MINUS = 31;
  public static final int STR_CONST = 23;
  public static final int RPAREN = 38;
  public static final int NOT = 18;
  public static final int TYPEID = 22;
  public static final int LT = 28;
  public static final int IN = 6;
  public static final int COMMA = 43;
  public static final int CLASS = 2;
  public static final int FI = 4;
  public static final int DIV = 33;
  public static final int LOOP = 10;
  public static final int PLUS = 30;
  public static final int ASSIGN = 25;
  public static final int IF = 5;
  public static final int DOT = 36;
  public static final int ID = 21;
  public static final int LE = 27;
  public static final int OF = 17;
  public static final int EOF = 0;
  public static final int INT_CONST = 24;
  public static final int TRUE = 19;
  public static final int NEW = 16;
  public static final int error = 1;
  public static final int ISVOID = 8;
  public static final int EQ = 29;
  public static final int COLON = 41;
  public static final int NEG = 34;
  public static final int LBRACE = 39;
  public static final int ELSE = 3;
  public static final int DARROW = 26;
  public static final int WHILE = 13;
  public static final int ESAC = 15;
  public static final int LET = 9;
  public static final int RBRACE = 40;
  public static final int THEN = 12;
  public static final int AT = 35;
  public static final int FALSE = 20;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CLASS",
  "ELSE",
  "FI",
  "IF",
  "IN",
  "INHERITS",
  "ISVOID",
  "LET",
  "LOOP",
  "POOL",
  "THEN",
  "WHILE",
  "CASE",
  "ESAC",
  "NEW",
  "OF",
  "NOT",
  "TRUE",
  "FALSE",
  "ID",
  "TYPEID",
  "STR_CONST",
  "INT_CONST",
  "ASSIGN",
  "DARROW",
  "LE",
  "LT",
  "EQ",
  "PLUS",
  "MINUS",
  "MULT",
  "DIV",
  "NEG",
  "AT",
  "DOT",
  "LPAREN",
  "RPAREN",
  "LBRACE",
  "RBRACE",
  "COLON",
  "SEMI",
  "COMMA"
  };
}

